# frozen_string_literal: true
source "https://rubygems.org"

# gem 'sinatra-activerecord'
# gem 'sqlite3', '~>1.4'
# gem 'pry'
# gem 'require_all'
# gem 'rake'
# gem 'pastel'
# gem 'tty'
# gem 'tty-font'
# gem 'tty-color'
# gem 'tty-prompt'
# gem 'tty-spinner'
# gem 'tty-progressbar'

gem 'sinatra-activerecord'
gem 'sqlite3', '~>1.4'
gem 'pry'
gem 'require_all'
gem 'rake'
gem 'tty'
gem 'tty-prompt'
gem 'tty-color'
gem 'pastel'
gem 'tty-font'
gem 'tty-progressbar'
gem 'tty-spinner'
